import Layout from "../layouts/landing";
import HomeHero from "../components/home/hero";
import Notified from "../components/home/notified";
import HowItWork from "../components/home/howItWork";
import NoSSRWrapper from "../hoc/noSSRWrapper";
export default function Home() {
  return (
    <NoSSRWrapper>
      <>
        {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
        <HomeHero />
        <HowItWork />
        <Notified />
      </>
    </NoSSRWrapper>
  );
}

Home.getLayout = function getLayout(page) {
  return <Layout>{page}</Layout>;
};
