import Layout from "../layouts/landing";
import HomeHero from "../components/home/hero";
import Notified from "../components/home/notified";
import HowItWork from "../components/home/howItWork";

export default function Home() {
  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <HomeHero />
      <HowItWork />
      <Notified />
    </>
  );
}

Home.getLayout = function getLayout(page) {
  return <Layout>{page}</Layout>;
};
